---
# tasks file for roles/postgres
- name: updating system
  apt:
     update_cache: true 

- name: install openJDK
  apt:
    name: 
    - openjdk-11-jdk
    state: present
    update_cache: true
    

- name: Add PostgreSQL repository
  command: echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list

- name: Add the PostgreSQL signing key
  apt_key:
   url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
   state: present

- name: Install PostgreSQL
  apt:
   name: 
   - postgresql
   state: present

- name: Enable and start postgresql
  service:
   name: postgresql
   enabled: true
   state: started

- name: Change PostgreSQL password and switch to postgres user
  user:
   name: postgres
   password: "147369"

- name: Create a new user
  user:
    name: sonar

   