- name: lab1 
  hosts: web
  become: true 
  tasks:
   - name: install apache2
     apt:
        name: apache2
        state: present

   - name: security group to allow apache2 listen on port 8090    
     lineinfile: 
        dest: /etc/apache2/ports.conf 
        regexp: "^Listen 80" 
        line: "Listen 8090" 
        state: present

   - name: Copy html file
     template:
        src: "salma.html"
        dest: "/var/www/html/index.html" 
  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted